-- CREATE THE DATABASE hbtn_0d_usa AND THE TABLE states
-- STAETE DISCRPTION
-- ID INT UNIQUE AUTO GNERATED NOT NULL
-- NAME CAN'T BE NULL
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.states(
    id INT UNIQUE AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(256) NOT NULL
);